// templates/react-templates/dirt_fe_react/src/components/Note/Note.tsx
import * as React from 'react';
import type { FC } from 'react';
import { FaInfoCircle } from 'react-icons/all';

interface NoteProps {
  iconElement?: React.ReactNode;
  labelText: string;
  content: string;
}

export const Note: FC<NoteProps> = ({ iconElement, labelText, content }) => {
  return (
    <div className="flex items-center gap-x-2">
      {iconElement ? iconElement : <FaInfoCircle size={20} />}
      <span>
        <span className="underline italic">{labelText}</span>{' '}
        <span className="text-purple-800">{content}</span>
      </span>
    </div>
  );
};

// templates/vue-templates/dirt_fe_vue/src/components/shared/Note.vue
<template>
  <div class="flex items-center gap-x-2">
    <slot>
      <information-circle-icon class="h-4 w-4 text-white" />
    </slot>
    <div
      class="flex flex-col justify-items-start text-left md:flex-row md:items-center md:gap-x-2"
    >
      <span class="underline italic">{{ labelText }}</span>
      <span class="text-slate-400">{{ content }}</span>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { InformationCircleIcon } from '@heroicons/vue/20/solid';

export default defineComponent({
  components: {
    InformationCircleIcon,
  },
  props: {
    content: { type: String, required: true },
    labelText: { type: String, required: true },
  },
});
</script>
